version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jazztech
    ports:
      - "3306:3306"
    volumes:
      - vinny_data:/var/lib/jazztech

volumes:
  vinny_data: